language: node_js
branches:
  only:
  - master
node_js:
- '6'
before_install:
- npm install -g npm
- openssl aes-256-cbc -K $encrypted_5e41bf3d8c4c_key -iv $encrypted_5e41bf3d8c4c_iv
  -in deploy_rsa.enc -out deploy_rsa -d
addons:
  ssh_known_hosts: 188.166.42.252
before_deploy:
- npm install -g pm2
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
